### ISSUE TITLE
Cannot install on Windows 10 or linux

### ISSUE THREAD

**Issue by pokan975** [laurimi/pydpomdp#3]
Hello, I tried to install this package to my custom conda envuronment, here is what I did: git clone this repo -> open Anaconda prompt, conda activate my environment -> locate to the local folder in which the local repo is -> run "pip install ./pydpomdp", but I keep getting the following error, my system OS is windows 10 (have cmake, git, and anaconda installed, python version: 3.9.16). Could you please tell what I should do? Thanks very much.

      (work_env) C:\Work\Python\Dec-POMDP>pip install ./pydpomdp
      Processing c:\work\python\dec-pomdp\pydpomdp
        Installing build dependencies ... done
        Getting requirements to build wheel ... done
        Preparing metadata (pyproject.toml) ... done
      Collecting pybind11
        Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
      Requirement already satisfied: wheel in c:\anaconda\envs\work_env\lib\site-packages (from pydpomdp==0.1.0) (0.38.4)
      Building wheels for collected packages: pydpomdp
        Building wheel for pydpomdp (pyproject.toml) ... error
        error: subprocess-exited-with-error

        × Building wheel for pydpomdp (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [68 lines of output]
            running bdist_wheel
            running build
            running build_py
            running build_ext
            <string>:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
            CMake Error at CMakeLists.txt:2 (project):
              Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      See also "C:/Work/Python/Dec-POMDP/pydpomdp/build/temp.win-amd64-cpython-39/Release/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "C:\Anaconda\envs\work_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Anaconda\envs\work_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Anaconda\envs\work_env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
          super().run_command(command)
        File "C:\Users\<user_name>\AppData\Local\Temp\pip-build-env-cgirn8lc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 31, in run
        File "<string>", line 67, in build_extension
        File "C:\Anaconda\envs\work_env\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Work\\Python\\Dec-POMDP\\pydpomdp\\pydpomdp', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Work\\Python\\Dec-POMDP\\pydpomdp\\build\\lib.win-amd64-cpython-39\\', '-DPYTHON_EXECUTABLE=C:\\Anaconda\\envs\\work_env\\python.exe', '-Dpybind11_DIR=C:\\Users\\<user_name>\\AppData\\Local\\Temp\\pip-build-env-cgirn8lc\\overlay\\Lib\\site-packages\\pybind11\\share\\cmake\\pybind11', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Work\\Python\\Dec-POMDP\\pydpomdp\\build\\lib.win-amd64-cpython-39\\', '-A', 'x64']' returned non-zero exit status 1.
      [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pydpomdp
      Failed to build pydpomdp
      ERROR: Could not build wheels for pydpomdp, which is required to install pyproject.toml-based projects

**Comment by laurimi** [comment]
Hi, never tried compiling on Windows myself, but could the solution be to specify those two missing variables that cause the CMake error, as discussed [here](https://stackoverflow.com/questions/70524164/cmake-c-compiler-not-set-after-enablelanguage)?

You might have luck defining those variables in [setup.py](https://github.com/laurimi/pydpomdp/blob/98249831e0885c56469da694605b4a41830ea0f4/setup.py#L45) by adding the corresponding lines.

Hope this helps!

**Comment by pokan975** [comment]
Hi, thanks for your reply, I tried to install it in ubuntu 16.04, but still got some error, it looks like it needs boost lib installed? (I have cmake installed in conda environment)

I have an independent installation of MADP toolbox in the ubuntu, can I use that directly instead of getting a new one from git like CMakeLists does? Thanks.

    (work_env) alinx@ubuntu:~/Documents/Python$ pip install ./pydpomdp
    Processing ./pydpomdp
      Installing build dependencies ... done
      Getting requirements to build wheel ... done
      Preparing metadata (pyproject.toml) ... done
    Requirement already satisfied: wheel in /home/alinx/anaconda3/envs/work_env/lib/python3.10/site-packages (from pydpomdp==0.1.0) (0.38.4)
    Collecting pybind11
      Using cached pybind11-2.10.4-py3-none-any.whl (222 kB)
    Building wheels for collected packages: pydpomdp
      Building wheel for pydpomdp (pyproject.toml) ... error
      error: subprocess-exited-with-error
  
      × Building wheel for pydpomdp (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [92 lines of output]
          running bdist_wheel
          running build
          running build_py
          running build_ext
          -- The C compiler identification is GNU 5.4.0
          -- The CXX compiler identification is GNU 5.4.0
          -- Detecting C compiler ABI info
          -- Detecting C compiler ABI info - done
          -- Check for working C compiler: /usr/bin/cc - skipped
          -- Detecting C compile features
          -- Detecting C compile features - done
          -- Detecting CXX compiler ABI info
          -- Detecting CXX compiler ABI info - done
          -- Check for working CXX compiler: /usr/bin/c++ - skipped
          -- Detecting CXX compile features
          -- Detecting CXX compile features - done
          -- Found PythonInterp: /home/alinx/anaconda3/envs/work_env/bin/python (found version "3.10.9")
          -- Found PythonLibs: /home/alinx/anaconda3/envs/work_env/lib/libpython3.10.so
          -- Performing Test HAS_FLTO
          -- Performing Test HAS_FLTO - Success
          -- Found pybind11: /tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/pybind11/include (found version "2.6.2" )
          -- Configuring done
          -- Generating done
          -- Build files have been written to: /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310
      [  6%] Building CXX object CMakeFiles/MADPBase.dir/_deps/project_madp-src/src/base/DecPOMDPDiscrete.cpp.o
      [  6%] Building CXX object CMakeFiles/MADPBase.dir/_deps/project_madp-src/src/base/DecPOMDP.cpp.o
      In file included from /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/base/Globals.h:23:0,
                       from /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/base/DecPOMDPDiscrete.h:23,
                       from /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/base/DecPOMDPDiscrete.cpp:16:
      /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/include/versions.h:16:29: fatal error: boost/version.hpp: No such file or directory
      compilation terminated.
      CMakeFiles/MADPBase.dir/build.make:89: recipe for target 'CMakeFiles/MADPBase.dir/_deps/project_madp-src/src/base/DecPOMDPDiscrete.cpp.o' failed
      make[2]: *** [CMakeFiles/MADPBase.dir/_deps/project_madp-src/src/base/DecPOMDPDiscrete.cpp.o] Error 1
      make[2]: *** Waiting for unfinished jobs....
      In file included from /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/base/Globals.h:23:0,
                       from /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/base/DecPOMDP.h:22,
                       from /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/base/DecPOMDP.cpp:16:
      /home/alinx/Documents/Python/pydpomdp/build/temp.linux-x86_64-cpython-310/_deps/project_madp-src/src/include/versions.h:16:29: fatal error: boost/version.hpp: No such file or directory
      compilation terminated.
      CMakeFiles/MADPBase.dir/build.make:75: recipe for target 'CMakeFiles/MADPBase.dir/_deps/project_madp-src/src/base/DecPOMDP.cpp.o' failed
      make[2]: *** [CMakeFiles/MADPBase.dir/_deps/project_madp-src/src/base/DecPOMDP.cpp.o] Error 1
      CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/MADPBase.dir/all' failed
      make[1]: *** [CMakeFiles/MADPBase.dir/all] Error 2
      Makefile:90: recipe for target 'all' failed
      make: *** [all] Error 2
      Traceback (most recent call last):
        File "/home/alinx/anaconda3/envs/work_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/alinx/anaconda3/envs/work_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/alinx/anaconda3/envs/work_env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-kg31sv2q/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 31, in run
        File "<string>", line 68, in build_extension
        File "/home/alinx/anaconda3/envs/work_env/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for pydpomdp
    Failed to build pydpomdp
    ERROR: Could not build wheels for pydpomdp, which is required to install pyproject.toml-based projects

**Comment by laurimi** [comment]
Hi, yes, that should be possible. But it requires quite a bit of editing for the `CMakeLists.txt` file. At a minimum, comment/remove all the lines that fetch the MADP toolbox, remove all the library build instructions that are MADP related and set `target_link_libraries` to link against your MADP installation instead. I think you can link against MADP as a whole, and do not need the sublibraries (base, parser). Check also the C++ backend compilation part of the readme of [my other project](https://github.com/laurimi/multiagent-prediction-reward) and the CMakeLists.txt therein for reference. 

Good luck! And, if you later have a suggestion how to get the compilation to work on Windows in a nice way, happy to accept a pull request :)
